name: postgresql96
version: 9.6.0
summary: PostgreSQL is a powerful, open source object-relational database system.
description: 
  PostgreSQL is a powerful, open source object-relational database system.
  It has more than 15 years of active development and a proven architecture
  that has earned it a strong reputation for reliability, data integrity,
  and correctness.
confinement: strict
grade: stable

apps:
  initialize:
       command: usr/bin/wrapper-initialize
       aliases: [initialize]
  clusterdb:
       command: usr/bin/clusterdb
       plugs: [network]
       aliases: [clusterdb]
  createdb:
       command: usr/bin/createdb
       plugs: [network]
       aliases: [createdb]
  createlang:
       command: usr/bin/createlang
       plugs: [network]
       aliases: [createlang]
  createuser:
       command: usr/bin/createuser
       plugs: [network]
       aliases: [createuser]
  dropdb:
       command: usr/bin/dropdb
       plugs: [network]
       aliases: [dropdb]
  droplang:
       command: usr/bin/droplang
       plugs: [network]
       aliases: [droplang]
  dropuser:
       command: usr/bin/dropuser
       plugs: [network]
       aliases: [dropuser]
  ecpg:
       command: usr/bin/ecpg
       aliases: [ecpg]
  initdb:
       command: usr/bin/initdb
       aliases: [initdb]
  pgarchivecleanup:
       command: usr/bin/pg_archivecleanup
       aliases: [pgarchivecleanup]
  pgbasebackup:
       command: usr/bin/pg_basebackup
       plugs: [network]
       aliases: [pgbasebackup]
  pgbench:
       command: usr/bin/pgbench
       plugs: [network]
       aliases: [pgbench]
  pgconfig:
       command: usr/bin/pg_config
       aliases: [pgconfig]
  pgcontroldata:
       command: usr/bin/pg_controldata
       aliases: [pgcontroldata]
  pgctl:
       command: usr/bin/wrapper-pg_ctl
       plugs:
          - network
          - network-bind
          aliases: [pgctl]
  pgdump:
       command: usr/bin/pg_dump
       plugs: [network]
       aliases: [pgdump]
  pgdumpall:
       command: usr/bin/pg_dumpall
       plugs: [network]
       aliases: [pgdumpall]
  pgisready:
       command: usr/bin/pg_isready
       plugs: [network]
       aliases: [pgisready]
  pgreceivexlog:
       command: usr/bin/pg_receivexlog
       plugs: [network]
       aliases: [pgreceivexlog]
  pgrecvlogical:
       command: usr/bin/pg_recvlogical
       plugs: [network]
       aliases: [pgrecvlogical]
  pgresetxlog:
       command: usr/bin/pg_resetxlog
       aliases: [pgresetxlog]
  pgrestore:
       command: usr/bin/pg_restore
       plugs: [network]
       aliases: [pgrestore]
  pgrewind:
       command: usr/bin/pg_rewind
       plugs: [network]
       aliases: [pgrewind]
  pgtestfsync:
       command: usr/bin/pg_test_fsync
       aliases: [pgtestfsync]
  pgtesttiming:
       command: usr/bin/pg_test_timing
       aliases: [pgtesttiming]
  pgupgrade:
       command: usr/bin/pg_upgrade
       aliases: [pgupgrade]
  pgxlogdump:
       command: usr/bin/pg_xlogdump
       aliases: [pgxlogdump]
  postgres:
       command: usr/bin/postgres
       plugs:
         - network
         - network-bind
         aliases: [postgres]
  postmaster:
       command: usr/bin/postmaster
       plugs: [network]
       aliases: [postmaster]
  psql:
       command: usr/bin/psql
       plugs: [network]
       aliases: [psql]
  reindexdb:
       command: usr/bin/reindexdb
       plugs: [network]
       aliases: [reindexdb]
  vacuumdb:
       command: usr/bin/vacuumdb
       plugs: [network]
       aliases: [vacuumdb]
  
parts:
  postgresql:
    plugin: autotools
    source: https://ftp.postgresql.org/pub/source/v9.6.0/postgresql-9.6.0.tar.bz2
    configflags:
        - --prefix=/usr
        - --localstatedir=/etc
        - --sysconfdir=/var
        ## Exclude SELinux
        #- -Xsepgsql
        # Skip -pie on 32bit archs for performance and stability reasons
        # (http://www.postgresql.org/message-id/20140519115318.GB7296@msgid.df7cb.de)
        #- -fPIC -pie
        #- -I/usr/include/mit-krb5
        #- -Wl,--as-needed -L/usr/lib/mit-krb5 -L/usr/lib/i386/mit-krb5
        - --enable-nls
        - --enable-integer-datetimes
        - --enable-thread-safety
        - --enable-tap-tests
        - --enable-debug
        - --disable-rpath
        - --with-uuid=e2fs
        - --with-gnu-ld
        - --with-pgport=5432
        - --with-system-tzdata=/usr/share/zoneinfo
        #- --with-gssapi
        - --with-ldap
        - --with-tcl
        - --with-tclconfig=/usr/lib/tcl8.6/
        - --with-perl
        - --with-python
        - --with-pam
        - --with-openssl
        - --with-libxml
        - --with-libxslt
    build-packages:
        - bison
        - flex
        - libreadline-dev
        - zlib1g-dev
        - python-dev
        - tcl8.6-dev
        - libssl-dev
        - libpam0g-dev
        - libxml2-dev
        #- libgssapi-krb5-2
        - libldap2-dev
        - libxslt1-dev
        - uuid-dev
        - libxml2-utils
        - openjade
        - opensp
        - xsltproc
        - gettext
        - libperl-dev
    stage-packages:
        - libc-bin
        - locales
  wrapper:
    plugin: make
    source: .
  #contrib:
  #  plugin: make
  #  source: parts/postgresql/src/contrib/
  #  after:
  #    - postgresql
